import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

import Navbar from "@/components/Navbar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const telegraf = localFont({
  src: [
    {
      path: "../../public/fonts/PPTelegraf-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/PPTelegraf-UltraBold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/PPTelegraf-UltraLight.otf",
      weight: "200",
      style: "normal",
    },
  ],
  variable: "--font-telegraf", // (optional, for Tailwind CSS)
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${telegraf.variable}  antialiased`}
      >
      <Navbar  />
        {children}
      </body>
    </html>
  );
}
